### ISSUE TITLE
MassiveCore

### ISSUE THREAD

**Issue by magnusulf** [MylesIsCool/PerWorldPlugins#1]
This is not exactly an issue but I had to contact you (@MylesIsCool).
MassiveCore's command system had some issues with your plugin (I suppose by looking at your code).
How can we (the MassiveCore developers) in any way help to make it compatible out of the box?
MassiveCoreBukkitCommand does now implement PluginIdentifiableCommand, to support your plugin (and possibly others). Is there anything else we can do to provide supprt for your plugin?

**Comment by FireMario211** [comment]
Here is a link for support in massivecore
http://www.mediafire.com/download/fs0w4r1yth/PerWorldsPlugin Massivecore Supported.jar
