### ISSUE TITLE
1.9 Support

### ISSUE THREAD

**Issue by ghost** [MylesIsCool/PerWorldPlugins#3]
Hey

As 1.9 made some drastic changes, please update your plugin.

**Comment by FireMario211** [comment]
TheChampTF its recommended that you get viaversion

**Comment by ghost** [comment]
Already have that, sadly not everything that works well with it.

**Comment by FormallyMyles** [comment]
This project is inactive, I'd suggest forking / using someone's unofficial continuation or even better migrating to technology like BungeeCord.
