### ISSUE TITLE
PerWorldInventories

### ISSUE THREAD

**Issue by evanpenner** [MylesIsCool/PerWorldPlugins#5]
Hi, this plugin causes PerworldInventories to not switch gamemodes and inventories, perworldinventories is enabled in every world. Could you add support for the plugin?

**Comment by FireMario211** [comment]
Here is a support for PerWorldPlugins I have supported it it should help you.

http://www.mediafire.com/download/5r347by5y7j9/PerWorldPlugins-Perworldinventories-Supported.jar

**Comment by FormallyMyles** [comment]
This project is inactive, I'd suggest forking / using someone's unofficial continuation or even better migrating to technology like BungeeCord.
