### ISSUE TITLE
Not sure what the problem is

### ISSUE THREAD

**Issue by Dart2112** [MylesIsCool/PerWorldPlugins#8]
`30.12 18:31:31 [Server] ERROR null
30.12 18:31:31 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'delhome' in plugin HomeSpawn v2.1.0
30.12 18:31:31 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
30.12 18:31:31 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
30.12 18:31:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot55.jar:git-Spigot-a9631d2-67b2424]
30.12 18:31:31 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
30.12 18:31:31 [Server] INFO Caused by: java.lang.NullPointerException`
the /delhome command is from my plugin and someone has reported this error to me. for whaterever reason it doesnt have any line numbers for where it is happening below "Caused by: java.lang.NullPointerException"
was wonderig if you had any insight into this

**Comment by FormallyMyles** [comment]
PWP is no longer officially maintained, in regards to your issue it's in relation to the home plugin you're using and you should contact the author of the plugin.
